"""new table

Revision ID: 1ac44b218c9b
Revises: 959e04d56cdc
Create Date: 2022-01-01 18:48:32.900663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac44b218c9b'
down_revision = '959e04d56cdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('film_name', sa.String(length=250), nullable=False),
    sa.Column('room_number', sa.String(length=250), nullable=False),
    sa.Column('proyection_time', sa.String(length=250), nullable=False),
    sa.Column('proyection_date', sa.String(length=250), nullable=False),
    sa.Column('seatss_number', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('my_rooms', 'seatss_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('proyections_film_id_fkey', 'proyections', type_='foreignkey')
    op.create_foreign_key(None, 'proyections', 'films', ['film_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proyections', type_='foreignkey')
    op.create_foreign_key('proyections_film_id_fkey', 'proyections', 'films', ['film_id'], ['id'])
    op.alter_column('my_rooms', 'seatss_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('my_ticket')
    # ### end Alembic commands ###
