"""new table1

Revision ID: 7310184101c4
Revises: 1ac44b218c9b
Create Date: 2022-01-01 18:50:48.024925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7310184101c4'
down_revision = '1ac44b218c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_ticket', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'my_ticket', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'my_ticket', type_='foreignkey')
    op.drop_column('my_ticket', 'user_id')
    # ### end Alembic commands ###
