"""init db

Revision ID: 959e04d56cdc
Revises: 
Create Date: 2021-12-22 14:40:52.474169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959e04d56cdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rooms_name', sa.String(length=250), nullable=False),
    sa.Column('seatss_number', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rooms_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('film_title', sa.String(length=250), nullable=False),
    sa.Column('film_category', sa.String(length=250), nullable=False),
    sa.Column('film_title_slug', sa.String(length=250), nullable=False),
    sa.Column('film_synopsis', sa.Text(), nullable=True),
    sa.Column('film_image', sa.String(), nullable=False),
    sa.Column('film_opening', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('film_title'),
    sa.UniqueConstraint('film_title_slug')
    )
    op.create_table('proyections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('film_title', sa.String(length=250), nullable=False),
    sa.Column('room_number', sa.String(length=250), nullable=False),
    sa.Column('proyection_time', sa.String(length=250), nullable=False),
    sa.Column('proyection_date', sa.String(length=250), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proyections')
    op.drop_table('films')
    op.drop_table('users')
    op.drop_table('my_rooms')
    # ### end Alembic commands ###
